version: '3'
services:
  db:
    container_name: db-container
    build: DB/
    # <Host IP>:<Host Port>:<Container Port>
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./DB/initdb:/docker-entrypoint-initdb.d

  ap:
    container_name: ap-container
    depends_on:
      - db
    build:
      context: AP/
      args:
        DATABASE_URL_DEV: ${DATABASE_URL_DEV}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5000:5000
    stdin_open: true

